gains:
  ros_parameters:
    gripper_left_finger_joint: {p: 100,  d: 0, i: 10, i_clamp: 1.5}
    gripper_right_finger_joint: {p: 100,  d: 0, i: 10, i_clamp: 1.5} 

    arm_1_joint: {p: 500, d: 5.0, i: 0.0,  i_clamp: 3, torque_clamp: 60}
    arm_2_joint: {p: 800, d: 5.0, i: 0.1,  i_clamp: 3, torque_clamp: 50}
    arm_3_joint: {p: 200, d: 0.5, i: 0.1,  i_clamp: 3, torque_clamp: 50}
    arm_4_joint: {p: 800, d: 1.0, i: 0.1,   i_clamp: 3, torque_clamp: 50}
    arm_5_joint: {p: 50,  d: 0.1, i: 0.01, i_clamp: 3, torque_clamp: 50}
    arm_6_joint: {p: 200,  d: 0.1, i: 0.01, i_clamp: 3, torque_clamp: 50}
    arm_7_joint: {p: 50,  d: 0.1, i: 0.01, i_clamp: 3, torque_clamp: 50}
